apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pygeoapi.fullname" . }}
  labels:
    {{- include "pygeoapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pygeoapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pygeoapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pygeoapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: debug
              containerPort: 5678
              protocol: TCP
          {{- if not .Values.debug.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 20
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.debug.enabled }}
          env:
          - name: DEBUGPY
            value: "True"
          - name: WSGI_WORKERS
            value: "1"
          - name: GEVENT_SUPPORT
            value: "True"
          {{- end }}
          volumeMounts:
          - mountPath: /pygeoapi/local.config.yml
            name: pygeoapi-config
            subPath: docker.config.yml            
          - mountPath: /wait-for-elasticsearch.sh
            name: pygeoapi-config
            subPath: wait-for-elasticsearch.sh
          - mountPath: /es-entrypoint.sh
            name: pygeoapi-config
            subPath: es-entrypoint.sh
          command:
          # - bash
          # - -c
          # - sleep infinity
          - /es-entrypoint.sh
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: pygeoapi-config
        configMap:
          defaultMode: 493
          name: pygeoapi-config
